package constants

const (
	NO_INTERLOCUTOR           = "NO_INTERLOCUTOR"
	INTERLOCUTOR_FOUND        = "INTERLOCUTOR_FOUND"
	CLIENT_EXISTS             = "CLIENT_EXISTS"
	CHAT_CONFIRMED            = "CHAT_CONFIRMED"
	INTERLOCUTOR_WAIT_TIMEOUT = "INTERLOCUTOR_WAIT_TIMEOUT"
)
